- configuration/base.yaml
- configuration/local.yaml
- configuration/production.yaml
- src/database/connection.rs
- src/database/mod.rs
- src/database/queries.rs
- src/database/schema.rs
- src/main.rs
- src/server/middleware.rs
- src/server/services/graphql/config.rs
- src/server/services/graphql/mod.rs
- src/server/services/graphql/routes/handlers.rs
- src/server/services/graphql/routes/mod.rs
- src/server/services/graphql/routes/paths.rs
- src/server/services/graphql/schema/context.rs
- src/server/services/graphql/schema/mod.rs
- src/server/services/graphql/schema/mutations.rs
- src/server/services/graphql/schema/queries.rs
- src/server/services/graphql/schema/subscriptions.rs
- src/server/services/graphql/schema/types.rs
- src/server/services/mod.rs
- src/server/services/rest/config.rs
- src/server/services/rest/mod.rs
- src/server/services/rest/routes/handlers.rs
- src/server/services/rest/routes/mod.rs
- src/server/services/rest/routes/paths.rs
- src/utils/configuration.rs
- src/utils/environment.rs
- src/utils/mod.rs
- src/utils/settings.rs
As mentioned, there are currently conflicts but you suggested that I leave the rebasing to you rather than doing it myself (but ask me and I can do it readily enough).
Notes are mostly on the commits. Here are the other notes I made:
src/utils/environment.rs:18, better to avoid String, use FromStr instead of TryFrom<String>.
src/utils/configuration.rs:15, "local".into() is a strictly unnecessary allocation of a String, though this being a one-off thing and the ergonomics of Cow being what they are I generally wouldn’t worry, but the teaching opportunity is good—Cow is worth knowing about. In this instance it ends up a surprisingly painless alteration, but it’s still a technical distraction from the logic, and thus potentially unwarranted.
Good stuff on using .expect(message) rather than …
> Chris’s review

- src/util/configuration.rs
Sorry no associated issue, it's me learning rust.
* No explicit panics out of configuration.rs, always return ConfigError
* Move string to constants at the top of file (not sure if it adds anything, just a stylistic habit)
* Couldn't see the need to convert env var to Environment and then to $str, simplified
* Remove extra environment specification, wasn't sure why it's there
@wlthomson the last two, may need to be reinstated, but I couldn't figure out why they are need.
Would be nice to have conversion from error returned by current_dir to ConfigError, but they are from external crates (could make a common type, but thought map_err is enough)
> Simplify configurations

- src/server/data/registry.rs
> #221 RepositoryRegistry should not #[derive(Clone)]

- src/database/repository/mock/item.rs
- src/database/repository/mock/item_line.rs
- src/database/repository/mock/name.rs
- src/database/repository/mock/requisition.rs
- src/database/repository/mock/requisition_line.rs
- src/database/repository/mock/store.rs
- src/database/repository/mock/transact.rs
- src/database/repository/mock/transact_line.rs
- src/database/repository/mock/user_account.rs
Closes #251.
Example output:
```
[2021-08-19T07:21:52Z INFO  remote_server::database::repository::repository::requisition] Querying requisition record (requisition.id=requisition_za)
[2021-08-19T07:21:52Z INFO  remote_server::database::repository::repository::name] Querying name record (name.id=name_store_a)
[2021-08-19T07:21:52Z INFO  remote_server::database::repository::repository::store] Querying store record (store.id=store_b)
[2021-08-19T07:21:52Z INFO  remote_server::database::repository::repository::requisition_line] Querying requisition_line records (requisition_line.requisition_id=requisition_za)
[2021-08-19T07:21:52Z INFO  remote_server::database::repository::repository::item] Querying item record (item.id=item_a)
```
> #252 Add mock repository logging

- README.md
- scripts/init_db.sh
Not optimal, but spinning up Postgres in rootless mode doesn't seem to work...
> [No issue] Add linux support to the init script + update readme

- migrations/postgres/00000105_create_item_table/up.sql
- migrations/sqlite/00000104_create_item_table/up.sql
- src/database/mock/item.rs
- src/database/repository/diesel/item.rs
- src/database/repository/diesel/mod.rs
- src/database/repository/diesel/name.rs
- src/database/repository/diesel/sync.rs
- src/database/repository/mod.rs
- src/database/schema/diesel_schema.rs
- src/database/schema/item.rs
- src/database/schema/mod.rs
- src/database/schema/name.rs
- src/server/service/graphql/schema/mutations.rs
- src/server/service/graphql/schema/types.rs
- src/util/mod.rs
- src/util/settings.rs
- src/util/sync/mod.rs
- src/util/sync/translation/item.rs
- src/util/sync/translation/mod.rs
- src/util/sync/translation/name.rs
- src/util/test_db.rs
- tests/repository/basic.rs
- tests/test.rs
This aims to implement the translaions as we discusses last time.
There are two things that I am not entirely happy with but couldn't fix to this point (because of Rust type and async issues).
1) After another discussion with Will we realized that Andrei and me probably planted to use something more closer to a DAO pattern and that DAO and repository pattern are complimentary (e.g. https://www.baeldung.com/java-dao-vs-repository). For this reason I did some experimenting using a DAO layer between ORM and Repository where the Repository layer is mostly independent from Diesel and only uses the DAO layer. However, I run into some further async issues and gave up on it. However, I think it might be an options to move the auxilary methods like `pub fn insert_one_tx(connection: &DBConnection, …
> 281 simple translation 2

- src/main.rs
- src/util/sync/mod.rs
Closes #331.
Trying to keep these PRs as easy to review as possible. Still remaining to do:
- Error handling
- Cursor persistence
- Integrating "stub" central sync record data into translation work (currently central sync logic only parses record `id` fields)
> #331 Save incoming central sync records into central buffer

- src/database/repository/diesel/mod.rs
- src/database/repository/diesel/sync.rs
- src/util/sync/mod.rs
- src/util/sync/translation/mod.rs
Instead of putting more logic into the SyncRepository I introduced a SyncSession and all records integrated in the same SyncSession are stored in a single transaction.
Let me know what you think...
> Use a "SyncSession" to integrate all records in a single tx

- src/database/repository/diesel/invoice_query.rs
- src/database/repository/diesel/mod.rs
- src/database/repository/diesel/name_query.rs
- src/database/repository/diesel/sort_filter_types.rs
- src/database/repository/tests.rs
- src/server/service/graphql/schema/queries/mod.rs
- src/server/service/graphql/schema/types/invoice_query.rs
- src/server/service/graphql/schema/types/invoices_query.rs
- src/server/service/graphql/schema/types/mod.rs
- src/server/service/graphql/schema/types/name.rs
- src/server/service/graphql/schema/types/sort_filter_types.rs
Add filter and sort options for the invoices endpoint.
- Define common filter and sort types/struct that can be reused between endpoints (both on repository layer and graphql layer)
- Use common structs for the name endpoint
- Refactor repo to graph gql enum mapping for the invoices endpoint
> 307 invoices filter sort

- src/database/repository/diesel/mod.rs
- src/database/repository/diesel/name_query.rs
- src/database/repository/tests.rs
- src/domain/mod.rs
- src/domain/name.rs
- src/lib.rs
- src/server/service/graphql/schema/queries/mod.rs
- src/server/service/graphql/schema/types/mod.rs
- src/server/service/graphql/schema/types/name.rs
- src/server/service/graphql/schema/types/sort_filter_types.rs
- src/service/mod.rs
- src/service/name.rs
Fixed: #404 
Add domain object, service and query with composition (of domain object). Also added generic types for error handling in queries and generic connector result
* Move filters and sorts to domain area 
* Created service for name
* Changed repository to use domain object 
* Changed repository to allow for count to be filtered
Not that happy about both total count and nodes being queried (even if just one of them is requested in gql query, can work around it with look ahead, maybe in future PR)
> 404 align name query with design decisions

- docs/content/docs/api/custom_errors.md
- docs/content/docs/api/mutations.md
- docs/content/docs/api/patterns.md
- docs/content/docs/api/queries.md
- docs/content/docs/api/types.md
Chargeable to 286
* Use new translations
* Put implementation details in drop down and removed unnecessary mapping info
* Changed from `quantity` to explicit packSize and numberOfPack
* Types in GraphQL code blocks
* Moved available number of packs in lines to a new resolver (since it's not needed in supplier invoice type and requires use of join, which we've chosen no optimise with data loader, which requires a resolver to be efficient)
Sorry, this is probably unexpected change in some areas, hopefully it doesn't undo front end work (can't wait to get GraphQL api out there with introspection, so that this types are easy to change on front end)
> #286 update tranlsation in query api docs

- src/database/repository/diesel/mod.rs
- src/database/repository/diesel/storage_connection.rs
- src/domain/customer_invoice.rs
- src/domain/mod.rs
- src/server/service/graphql/schema/mutations/customer_invoice/delete.rs
- src/server/service/graphql/schema/mutations/customer_invoice/error.rs
- src/server/service/graphql/schema/mutations/customer_invoice/insert.rs
- src/server/service/graphql/schema/mutations/customer_invoice/update.rs
- src/server/service/graphql/schema/mutations/mod.rs
- src/server/service/graphql/schema/mutations/supplier_invoice/delete.rs
- src/server/service/graphql/schema/mutations/supplier_invoice/mod.rs
- src/server/service/graphql/schema/types/mod.rs
- src/service/invoice/customer_invoice/delete/mod.rs
- src/service/invoice/customer_invoice/delete/validate.rs
- src/service/invoice/customer_invoice/insert/generate.rs
- src/service/invoice/customer_invoice/insert/mod.rs
- src/service/invoice/customer_invoice/insert/validate.rs
- src/service/invoice/customer_invoice/mod.rs
- src/service/invoice/mod.rs
- src/service/invoice/supplier_invoice/update/generate.rs
- src/util/mod.rs
- src/util/uuid.rs
Here is already the insert and delete part of the ticket.
- I introduced an uuid utils method (which I then don't use but I kept in anyway)
- There is a new transaction_sync() method for the StorageConnection, I plan to refactor that later (think we going fully sync right?)
- There are some validation checks that can be shared with SI. I plan to refactor that as well as soon as SI is settled. To make the reuse easier the common validation methods should return a bool or Option instead of a CommonError. 
- Due to the point above I inlined all delete checks for now. At least for these simple checks its makes things much easier to read.
> 348 ci insert delete

- src/service/mod.rs
- src/service/token_bucket.rs
- src/service/user_account.rs
Currently all user tokens are invalidated on logout. Tokens are stored in memory but there is a trait to have a different backend.
Not sure if I am going to far here, e.g. some open questions:
- should we really invalidate all tokens if a user logs out or just the token for a certain client
- after a token refresh, should the expiry time for old tokens be reduced, e.g. down to 5min
> Add support for user logout

- src/database/mock/full_master_list.rs
- src/database/mock/item.rs
- src/database/mock/mod.rs
- src/database/mock/stock_line.rs
- src/database/mock/unit.rs
- src/database/repository/diesel/item_query.rs
- src/domain/item.rs
- src/server/service/graphql/schema/types/item.rs
- tests/graphql/invoice_query.rs
- tests/graphql/invoices.rs
- tests/graphql/items.rs
- tests/graphql/mod.rs
- tests/graphql/outbound_shipment_delete.rs
- tests/graphql/outbound_shipment_insert.rs
- tests/graphql/outbound_shipment_update.rs
Closes #535 
Ended up with more changes then i hoped:
* Needed to add item query test which required
* Item query test items
* Full master list
* One unit
* The above meant that foreign key integrity will be broken unless unit is also inserted in other test, thus refactored other tests slightly to insert all data
* Relocated `invoices` entry date filter from invoice_query to invoices test
> 535 add unit to item query

- configuration/base.yaml
- src/database/repository/diesel/user_account.rs
- src/main.rs
- src/server/data/auth.rs
- src/server/data/mod.rs
- src/server/service/graphql/mod.rs
- src/server/service/graphql/schema/mutations/mod.rs
- src/server/service/graphql/schema/mutations/user_register.rs
- src/server/service/graphql/schema/queries/auth_token.rs
- src/server/service/graphql/schema/queries/login.rs
- src/server/service/graphql/schema/queries/logout.rs
- src/server/service/graphql/schema/queries/mod.rs
- src/server/service/graphql/schema/queries/refresh_token.rs
- src/server/service/graphql/schema/types/mod.rs
- src/service/mod.rs
- src/service/token.rs
- src/service/user_account.rs
- src/util/settings.rs
- src/util/test_db.rs
- tests/graphql/mod.rs
Add gql endpoints:
- registerUser
- authToken (rename to login?)
- refreshToken
- logout
I only manually tested the full flow in the playground so far...
@andreievg you where right asking why token methods where in the UserAccountService. I now moved them into a TokenService and think this is cleaner and more flexible now.
I extract the Bearer token and refresh cookie from the http request and then make the them accessible (if present) in the gql context. I had a look how to do this in a middleware but actix-web seems to make that overly complicated so I didn't follow this approach for now.
Only the logout method validates the bearer token so far. I think the errors in the logout methods are a bit to detailed right now and should be merged into a single generic "Authentication/Permission" …
> 506 gql user account endpoints

- graphql/src/lib.rs
- graphql/src/schema/mod.rs
- graphql/src/schema/queries/logout.rs
- graphql/src/schema/queries/me.rs
- graphql/src/schema/queries/mod.rs
- graphql/src/schema/types/mod.rs
- repository/src/db_diesel/user_account.rs
- server/src/main.rs
- server/tests/graphql/mod.rs
- service/src/auth_data.rs
- service/src/lib.rs
- service/src/permission_validation.rs
- service/src/permissions.rs
- service/src/user_account.rs
- Add helper method to validate that a user is authenticated and has the correct permissions.
- Add `me` endpoint that uses the helper method
- Refactor the `logout` endpoint to use the helper
- Add debug flag to disable the authentication check and make the user an Admin user
The permission system is work in progress, happy to discuss. For the validation I use some higher order functions to have something like a permission DSL. For example, a complex permission check could look like:
``` rust
validate(..., vec![
// ANY required roles to access this endpoint
any(vec![ 
has_api_role(ApiRole::Support),
has_api_role(ApiRole::Plugin)
]),
// AND:
has_store_access((store_id, StoreRole::StoreWorker)),
// AND all of the following:
all(vec![
some(),
other(),
role(),
checker()
])
])
```
> 506 auth/permission validation helper and me endpoint

- README.md
- docs/content/docs/M1/how_to_m1.md
Fixes #561 
Scratches an itch.. I've referred to the M1 docs a few times when working on windows and it would be useful to copy and paste. Have taken the change from the main readme across.
Also detailed the parts of the command a little, as it took me a moment to realise what was going on when I first used it, thought that it would be clearer for new users if I broke the command down.
> update M1 doc with multi-platform quotes

- repository/src/db_diesel/central_sync_cursor.rs
- repository/src/db_diesel/storage_connection.rs
- server/src/sync/translation/mod.rs
Add transaction_etc method which has the option to enforce a nested
transaction.
This avoids creating unnecessary nested transaction while ensuring that operations are performed in a transaction.
> Reuse existing tx on default when doing nested con.transaction() calls

- README.md
- repository/src/diesel_macros.rs
- repository/src/tests.rs
Use ilike for postgres (works for ASCII and UTF8 chars, e.g. tested with Ä <--> ä ).
Sqlite is case insensitive on default. However, it only works for ASCII chars. Using something like ICU or providing a custom UPPER method is a bit more complicated (e.g. https://forum.lazarus.freepascal.org/index.php?topic=34259.0 has some solution for Pascal).
Do we need to filter for non ASCII char?
Closes #604
> Enable ilike (case insensitive like) for Postgres

- repository/src/mock/invoice.rs
- repository/src/mock/invoice_line.rs
- repository/src/mock/item.rs
- repository/src/mock/mod.rs
- repository/src/mock/test_invoice_count_service.rs
- repository/src/mock/test_outbound_shipment_update.rs
- repository/src/test_db.rs
- server/src/test_utils.rs
- server/tests/graphql/inbound_shipment_line_insert.rs
- server/tests/graphql/inbound_shipment_line_update.rs
- server/tests/graphql/inbound_shipment_update.rs
- server/tests/graphql/invoice_query.rs
- server/tests/graphql/outbound_shipment_insert.rs
- server/tests/graphql/outbound_shipment_update.rs
- service/src/location/tests/insert.rs
- service/src/location/tests/query.rs
I tried to use a simple HashMap for the MockDataCollection but I need to write mock data in a fixed order to the DB. For this reason MockDataCollection looks a little bit complicated since I made it behave like a HashMap... Otherwise it should be quite straight forward. Currently there are three MockData entries in the collection, the base MockData and mock data for two tests.
This approach could actually also make it easier to find test specific mock data in a test (e.g. mock_data["my-test"].names[0])
> Mock data collection

- domain/src/invoice.rs
- graphql/src/schema/types/invoice_query.rs
- graphql/src/schema/types/sort_filter_types.rs
- repository/migrations/postgres/00000106_create_invoice_table/up.sql
- repository/migrations/postgres/00000118_number_table/up.sql
- repository/migrations/sqlite/00000118_number_table/up.sql
- repository/src/db_diesel/item_query.rs
- repository/src/db_diesel/number_row.rs
- repository/src/mock/mod.rs
- repository/src/mock/number.rs
- repository/src/schema/diesel_schema.rs
- repository/src/schema/invoice.rs
- repository/src/schema/mod.rs
- repository/src/schema/number.rs
- repository/src/tests.rs
- server/tests/graphql/inbound_shipment_insert.rs
- server/tests/graphql/master_lists.rs
- server/tests/graphql/outbound_shipment_insert.rs
- service/src/invoice/inbound_shipment/insert/generate.rs
- service/src/invoice/outbound_shipment/insert/generate.rs
- service/src/number.rs
Closes #657 
Sorry a few changes from the original implementation.
* Added type to number row (want to be type strict, and avoid concatenating string to identify database entities). This made id a uuid, in previous repo test "test_counter_name" would only work for one store, as the id wouldn't be unique across stores (although it was tested with store_id)
* Ended up relocating number logic to service, I thought it was too much logic in repo (including transaction logic), I feel like the logic is responsibility of service.
* Added number logic to both inbound and outbound shipments.
Really wanted to make number service accept ServiceContext, and went a fair way down that track (ServiceContext would have transaction method, which is really a one liner), but it required quite a lot of …
> 657 apply number sequence logic on invoices

- repository/src/mock/test_unallocated_line.rs
- server/tests/graphql/outbound_shipment_update.rs
- service/src/invoice_line/outbound_shipment_unallocated_line/delete.rs
- service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
- service/src/invoice_line/outbound_shipment_unallocated_line/update.rs
As per: https://github.com/openmsupply/remote-server/pull/668#discussion_r773434184, plus test compilation fix
> 664 fix unallocated line for item already exists in invoice error criteria

- graphql/src/schema/mutations/mod.rs
- graphql/src/schema/mutations/outbound_shipment/mod.rs
- graphql/src/schema/mutations/outbound_shipment/unallocated_line/insert.rs
- graphql/src/schema/mutations/outbound_shipment/unallocated_line/mod.rs
- graphql/src/schema/types/invoice_line.rs
- graphql/src/standard_graphql_error.rs
- server/tests/graphql/mod.rs
- server/tests/graphql/unallocated_line/insert.rs
- server/tests/graphql/unallocated_line/mod.rs
Fixes: #667 
* Removed 'code' from error extensions, this changes:
* 
**from**
```json
"extensions": {
"code": "BadUserInput(\"NotAStockItem\")",
"details": "NotAStockItem"
}
```
**to**
```json
"extensions": {
"details": "NotAStockItem"
}
```
standard graphql error already has "Bad user input" in the 'message' field
Noticed that `extend` must be called in order for details to be present in error output (not sure if this is called in other standard error outputs):
https://github.com/openmsupply/remote-server/blob/66b8f22e6459b17bacdbfb88fabd98f9c4ec4913/graphql/src/schema/mutations/outbound_shipment/unallocated_line/insert.rs#L121
Created helper for `assert_standard_graphql_error`, I've made it a macro (to locate the error quickly) and made sure it return all required info when error …
> 667 add uallocated line insert graphql

- Cargo.lock
- Cargo.toml
- android/Cargo.toml
- android/host.sh
- android/makefile
- android/src/android.rs
- android/src/lib.rs
- server/Cargo.toml
- server/src/lib.rs
- server/src/main.rs
- server/src/sync/connection.rs
- server/src/sync/server.rs
- server/src/sync/synchroniser.rs
- Adds a package for Android java bindings.
- Refactors a start_server method that can be used in main and from Android
- Add "off_switch" parameter to start_server to shutdown the server (e.g. when running on Android)
- Remove unwrap from sync (so that the error can be logged on Android)
> Android java bindings

- server/src/main.rs
The off_switch sender was dropped too earlier causing it to fire
immediately.
> Fix the main server

- graphql/src/schema/queries/mod.rs
- graphql/src/schema/queries/stocktake.rs
- server/tests/graphql/mod.rs
- server/tests/graphql/stocktake_query.rs
I ended up to not introduce new methods in the stocktake service. After simplifying the `stocktake` endpoint the code was actually so simple that I didn't see the need for a special service method, i.e. the service only has one query method. 
Somehow I ran into a std error while adding stocktake tests and the output was a bit misleading. I now print the std error in the assert_graphql_query macro.
> 769 stocktake by number

- graphql/src/schema/mutations/inbound_shipment/batch.rs
- graphql/src/schema/mutations/mod.rs
- graphql/src/schema/mutations/outbound_shipment/batch.rs
- graphql/src/schema/mutations/outbound_shipment/unallocated_line/delete.rs
- graphql/src/schema/mutations/outbound_shipment/unallocated_line/insert.rs
- graphql/src/schema/mutations/outbound_shipment/unallocated_line/update.rs
- server/tests/graphql/inbound_shipment_batch.rs
- server/tests/graphql/unallocated_line/delete.rs
- server/tests/graphql/unallocated_line/insert.rs
- server/tests/graphql/unallocated_line/update.rs
closes: #768 
Also added unallocated line mutations to outbound shipment.
There is a mix and match of trait services and older services taking connection manager, to decided to keep it simple for now and made a bulletpoint to address this (and use transaction, similar to stocktake batch mutation), anyways added https://github.com/openmsupply/remote-server/issues/749
> 768 change batch mutations to use input object

- repository/src/lib.rs
- server/src/lib.rs
Checks for outstanding migrations and applies them.
Should also make developing remote sync a bit more easier, i.e. to start with a fresh DB.
Should automatically create an sql db on Android as well (untested)
> Automatically run DB migrations when starting the server

- graphql/graphql_schema/schema.graphql
- graphql/invoice/src/mutations/inbound_shipment/delete.rs
- graphql/invoice/src/mutations/outbound_shipment/delete.rs
- graphql/requisition/src/mutations/request_requisition/delete.rs
- graphql/stocktake/src/mutations/delete.rs
- server/tests/graphql/inbound_shipment_delete.rs
- server/tests/graphql/outbound_shipment_delete.rs
- service/src/invoice/inbound_shipment/delete/mod.rs
- service/src/invoice/inbound_shipment/delete/validate.rs
- service/src/invoice/outbound_shipment/delete/mod.rs
- service/src/invoice/outbound_shipment/delete/validate.rs
- service/src/invoice_line/inbound_shipment_line/delete/mod.rs
- service/src/invoice_line/outbound_shipment_line/delete/mod.rs
- service/src/requisition/request_requisition/delete.rs
- service/src/stocktake/delete.rs
- service/src/stocktake/tests.rs
closes #836 
* Remove check for lines existing
* Add removal of lines when record is deleted
* Add TODO's with link to issue
* Had to butcher transactions in shipment delete (in sqlite can't have two concurrent transactions and line services take connection manager)
Didn't add test but did a manual test
Used internal error for now in older pattern graphql mapping.
> 836 Unblock batch delete

- server/src/sync/translation_remote/invoice.rs
- server/src/sync/translation_remote/invoice_line.rs
- server/src/sync/translation_remote/mod.rs
- server/src/sync/translation_remote/requisition.rs
- server/src/sync/translation_remote/stock_line.rs
- server/src/sync/translation_remote/stocktake.rs
- server/src/sync/translation_remote/stocktake_line.rs
- server/src/sync/translation_remote/test_data/transact.rs
Date/time coming in from v5 are different from what the POST v3 endpoints expects. This fixes the ser/de of date and time values.
> 714 date time fixes

- Cargo.lock
- graphql/Cargo.toml
- graphql/lib.rs
- graphql/printing/Cargo.toml
- graphql/printing/src/lib.rs
- server/Cargo.toml
- server/src/lib.rs
- server/src/static_files.rs
Adds:
- printReport graphql endpoint that only takes a report id and the id of the entity to be printed, e.g. the invoice id, and returns a file id
- /files?id={id} endpoint to fetch the printed report
The files endpoint already contains some proof of concept logic which needs to be update and put into a service:
- It always creates a dummy txt file for a given id in the static_files directory
- Returns this dummy txt file with a proper file name (not the file id). The "proper" filename is currently encode like `{file_id}_filename.pdf`
- Cleans up old static files that are too old
#886
> 886 printing endpoint stub

- graphql/core/src/loader/invoice_line.rs
- graphql/core/src/loader/item_stats.rs
- graphql/core/src/loader/loader_registry.rs
- graphql/core/src/loader/mod.rs
- graphql/core/src/loader/name.rs
- graphql/core/src/loader/requisition_line.rs
- graphql/core/src/loader/requisition_supply_status.rs
- graphql/core/src/loader/stock_line.rs
- graphql/requisition/src/query_tests/requisition_loaders.rs
- graphql/types/src/types/invoice_query.rs
- graphql/types/src/types/item.rs
- graphql/types/src/types/requisition.rs
- graphql/types/src/types/requisition_line.rs
- graphql/types/src/types/store.rs
- service/src/requisition/mod.rs
- service/src/requisition/requisition_supply_status.rs
- service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
- service/src/requisition/response_requisition/create_requisition_shipment/mod.rs
- service/src/requisition/response_requisition/create_requisition_shipment/validate.rs
closes #878 
Needed to relocate get_remaing_fulfilments so that it can be shared for loaders, ended up just making a new service.
Decided to just use on generic type for input struct to loaders that require more than one value `IdPairWithPayload`. A bit out of scope, and at the end wasn't really needed, could have reused `RequisitionAndItemId`, but set a better pattern I think for those use cases in the future.
> 878 remaining to supply on requisition

- .gitignore
- graphql/core/src/loader/loader_registry.rs
- graphql/core/src/loader/mod.rs
- graphql/core/src/loader/store.rs
- graphql/general/src/lib.rs
- graphql/general/src/queries/store.rs
- graphql/types/src/types/invoice_query.rs
- graphql/types/src/types/name.rs
- graphql/types/src/types/store.rs
- repository/src/db_diesel/store.rs
- service/src/service_provider.rs
- service/src/store.rs
closes #715 
as per commit description 
* Add store service to general service
* Use store service in loader
* Join name to store in store repository
* Expose sort in store query with Code, Name and NameCode
* Add extra fitlers in store query for code, name_code, and name
> 715 add sort and extra filters to store query

- Cargo.lock
- graphql/Cargo.toml
- graphql/lib.rs
- graphql/reports/Cargo.toml
- graphql/reports/src/lib.rs
- graphql/reports/src/printing.rs
- graphql/reports/src/reports.rs
- Rename the printing graphql crate to reports. The crate contains the
reports and printReport endpoints.
Is report "category" to correct term?
Closes #899
> Add reports mock endpoint to fetch a list of available reports

- graphql/core/src/lib.rs
#936 
checks first bulletpoin in issue
> 936 Allow multiple cookies when parsing refresh token (quick fix)

- graphql/types/src/types/item_chart_data.rs
- graphql/types/src/types/mod.rs
- graphql/types/src/types/requisition_line.rs
closes #932 
Add requistionLineNode.chartData -> ItemChartDataNode.
I am not sure yet what parameters will be needed, will refine when implementing, most likely the following:
* Need expected delivery date (to know when evolution projected jumps up), this is needed on requisition not a parameter
* Probably need `step` and `count` on both consumptionHistory and stockEvoluation (i.e. step for consumptionHistory is 1 month, step for stockEvolution is 1 day, and count, how many steps to include, probably count back and count forward for stockEvolution)
* Need look back for amc calculation
> Add mock item chart node

- graphql/types/src/types/item.rs
- graphql/types/src/types/name.rs
links to #595 and #513
I didn't give too much though to field types and their storage (just looked at basic mSupply fields), so it's possible they will change when we actually implement (i.e. some maybe optional, address will probably be address node, etc..)
> Add basic mock fields for item and name

- graphql/general/src/queries/store.rs
- graphql/types/src/types/store.rs
- repository/migrations/postgres/2021-08-25T10-00_create_store_table/up.sql
- repository/migrations/sqlite/2021-08-20T10-00_create_store_table/up.sql
- repository/src/db_diesel/filter_sort_pagination.rs
- repository/src/db_diesel/invoice_query.rs
- repository/src/db_diesel/master_list.rs
- repository/src/db_diesel/name_query.rs
- repository/src/db_diesel/stock_movement.rs
- repository/src/db_diesel/store.rs
- repository/src/db_diesel/store_row.rs
- repository/src/db_diesel/user.rs
- repository/src/mock/store.rs
- repository/src/mock/test_master_list_repository.rs
- repository/src/mock/test_name_query.rs
- repository/src/mock/test_name_store_id.rs
- repository/src/mock/test_remote_pull.rs
- repository/src/schema/diesel_schema.rs
- repository/src/schema/mod.rs
- repository/src/schema/store.rs
- repository/src/schema/user_store_join.rs
- repository/src/tests.rs
- server/src/sync/integration_tests/remote_sync_integration_test.rs
- server/src/sync/translation_central/store.rs
- server/src/sync/translation_central/test_data/store.rs
- service/src/requisition_line/chart/mod.rs
Remote sync integration test: Get store_id automatically from the site_id provided in the settings.
This includes the following change:
- Add `remote_site_id` (further rename to `site_id`?) to the store row
- Add remote_site_id filter in StoreRepositiory. 
- Central sync: integrate the remote_site_id
- Use inline_init in store mocks (think this was also done in another PR(?) but should merge easily)
- Expose remote_site_id it in graphql
#987
> 987 store sync site

- repository/src/db_diesel/user_permission.rs
- repository/src/schema/user_permission.rs
- service/src/apis/permissions.rs
- service/src/permission_validation.rs
- service/src/service_provider.rs
closes #1009 
Fixed permission mapping (it's a good idea to test central server UI configurations propagate correctly):
Added a temp restriction for requisition mutate.
I did the following test:
* Log In, try mutate requisition with API (parameters don't matter, as long as strore_id is correct), you should get record not found error
* Update user permissions for the store_id you were using in central UI (see image above)
* Login again and try to mutate, should see permission error
I am not sure what front end would be showing as an error and if we need to present the error in a better format, would assume for V1 beta we would just show Unauthorised in UI
I think the error should be structure error, in the future when we sync users, user permissions could update without front end really …
> 1009 add mock permission restriction for requisition mutation

- Cargo.lock
- graphql/general/src/queries/login.rs
- service/Cargo.toml
- service/src/login.rs
If there is a login error I wait till (the randomly chosen time of) 6s for the total response has been passed.
#1006 
Needed to add tokio as a dependency for an async sleep...
> Use fix login response time in case of a login error

- README.md
- android/src/android.rs
- configuration/local.yaml
- server/src/lib.rs
- server/src/settings.rs
- server/src/test_utils.rs
- service/src/permission_validation.rs
#864 was already address in a different PR but there where some missing pieces, i.e. server always assumes we are in develop mode and starts without certs and if initial sync failed. For this reason I introduced a develop server settings entry.
If not in development mode the server shutdown if:
1) no certs are found
2) the initial sync failed
Closes #864
Closes #789
> Introduce a develop settings

- graphql/core/src/test_helpers.rs
- repository/Cargo.toml
- repository/src/database_settings.rs
- repository/src/db_diesel/storage_connection.rs
- repository/src/test_db.rs
- repository/src/tests.rs
- server/src/sync/central_data_synchroniser.rs
- server/src/sync/translation_central/mod.rs
- service/src/permission_validation.rs
- service/src/user_account.rs
Adds a new feature to run test "in memory"
Some results for the test runtime:
postgres: 1m39.591s, 1m52.946s
sqlite: 1m28.498s, 1m23.752s
memory: 18.924s, 18.539s
> Add feature to run tests in sqlite memory mode

- service/src/report/definition.rs
- service/src/report/dummy_reports.rs
- service/src/report/report_service.rs
Add an index to the report definition to make it clearer what entry in the definition file should be used for which purpose.
#887
> Remove hard coded template keys and use a template index map instead

- graphql/tests/mod.rs
- graphql/tests/pagination.rs
- graphql/tests/permissions.rs
- service/src/permission_validation.rs
Test calls all endpoints and checks that permissions are validated based on the correct resource.
Also test that the store is validated/not validated, depending on the endpoint.
Closes #1025
> Test that endpoints check for the right resources/permissions

- service/src/login.rs
Fixes #1063 
Not much more to say, just a typo in the permissions mapping.
> Permission mapping for requisitions

- graphql/general/src/lib.rs
- graphql/general/src/queries/store.rs
- graphql/tests/permissions.rs
- graphql/types/src/types/store.rs
- repository/src/db_diesel/name.rs
- repository/src/db_diesel/store.rs
- service/src/report/default_queries.rs
- service/src/service_provider.rs
- service/src/store.rs
closes #1079 
Also added store query, original requirement for this was for reports to be able to get current store name, thus additions of store query.
(I think we can quite easily use `StoreNode` in `me` query now, I didn't want to go too far out of scope of the issue)
> 1079 remove automatic filter of name belonging to current store

- graphql/general/src/queries/item.rs
- graphql/invoice/src/invoice_queries.rs
- graphql/requisition/src/query_tests/requisition.rs
- graphql/requisition/src/query_tests/requisitions.rs
- graphql/requisition/src/requisition_queries.rs
- graphql/types/src/types/location.rs
- repository/src/db_diesel/invoice.rs
- repository/src/db_diesel/item.rs
- repository/src/db_diesel/location.rs
- repository/src/db_diesel/name.rs
- repository/src/db_diesel/requisition/mod.rs
- repository/src/db_diesel/requisition/requisition.rs
- repository/src/db_diesel/store.rs
- repository/src/mock/test_requisition_queries.rs
#867 
name_id and name for requisition queries seem to be under otherPartyName & otherPartyID
> #867 make sure all basic fields are exposed in query filters and sorts for all types

- server/Cargo.toml
@andreievg though I better put a comment into the Cargo.toml file regarding your question why we still need openssl.
> Add comment why we still have openssl as a dependency

- service/src/apis/login_v4.rs
- service/src/login.rs
#1085 
User shouldn't be able to log in with old password in api now if password has been changed in central.
Note: Still can use old password if not logged into the central server and new password has not been saved in remote
Test:
> Can login with wrong credential #1085
