src/main.rs, src/services/graphql/config.rs, src/services/graphql/mod.rs, src/services/graphql/routes/handlers.rs, src/services/graphql/routes/mod.rs, src/services/graphql/routes/paths.rs, src/services/rest/config.rs, src/services/rest/mod.rs, src/services/rest/routes/handlers.rs, src/services/rest/routes/mod.rs, src/services/rest/routes/paths.rs
=> #18 Add health_check endpoint

Cargo.lock, Cargo.toml, configuration/base.yaml, configuration/local.yaml, configuration/production.yaml, src/database/mod.rs, src/main.rs, src/server/mod.rs, src/server/services/graphql/mod.rs, src/server/services/graphql/routes/mod.rs, src/server/services/graphql/schema/mod.rs, src/server/services/mod.rs, src/server/services/rest/mod.rs, src/server/services/rest/routes/mod.rs, src/utils/configuration.rs, src/utils/environment.rs, src/utils/mod.rs, src/utils/settings.rs
=> #23 Add configuration management

src/database/mocks.rs
=> #68 Add mock item_line data

src/database/schema.rs
=> #75 Fix inconsistent database structs

src/database/mocks.rs
=> #77 Fix inconsistent mock data

src/database/queries.rs
=> #79 Fix inconsistent database queries

src/server/services/graphql/schema/mutations.rs, src/server/services/graphql/schema/queries.rs, src/server/services/graphql/schema/types.rs
=> #81 Fix inconsistent gql schema

src/database/mocks.rs
=> #69 Add mock store data

src/database/mocks.rs
=> #70 Add mock name data

sqlx-data.json, src/database/connection.rs, src/database/queries.rs
=> #46 Add name database queries

sqlx-data.json, src/database/connection.rs, src/database/queries.rs
=> #45 Add store database queries

src/server/services/graphql/schema/types.rs
=> #42 Add Name type to gql schema

src/server/services/graphql/schema/types.rs
=> #43 Add Store type to gql schema

src/server/services/graphql/schema/queries.rs
=> #51 Add Name gql query

src/server/services/graphql/schema/queries.rs, src/server/services/graphql/schema/types.rs
=> #50 Add Store gql query

sqlx-data.json, src/database/connection.rs, src/database/queries.rs
=> #48 Add transact database queries

src/server/services/graphql/schema/mutations.rs
=> #90 Update Requisition mutation arguments

src/server/services/graphql/schema/types.rs
=> #4 Add Transact type to gql schema

src/server/services/graphql/schema/types.rs
=> #5 Add TransLine type to gql schema

sqlx-data.json, src/database/queries.rs, src/database/schema.rs
=> #47 Add trans_line database queries

src/server/services/graphql/schema/mutations.rs
=> #89 Update item mutation arguments

.githooks/pre-commit
=> #32 Add git hooks for code consistency

src/server/services/graphql/schema/mutations.rs, src/server/services/graphql/schema/queries.rs, src/server/services/graphql/schema/types.rs
=> #100 Refactor Requisition for optimised querying

src/server/services/graphql/schema/types.rs
=> #104 Refactor Name for optimised querying

src/server/services/graphql/schema/mutations.rs, src/server/services/graphql/schema/queries.rs, src/server/services/graphql/schema/types.rs
=> #106 Refactor Item for optimised querying

src/server/services/graphql/schema/queries.rs, src/server/services/graphql/schema/types.rs
=> #108 Refactor Store for optimised querying

src/server/services/graphql/schema/types.rs
=> Refactor RequisitionLine for optimised querying

src/server/services/graphql/schema/queries.rs, src/server/services/graphql/schema/types.rs
=> Refactor ItemLine for optimised querying

src/server/services/graphql/schema/queries.rs
=> #14 Add Transact gql query

src/server/services/graphql/schema/queries.rs
=> #52 Add TransLine gql query

migrations/20210601032959_create_requisition_table.sql, sqlx-data.json, src/database/mocks.rs, src/database/queries.rs, src/database/schema.rs, src/server/services/graphql/schema/mutations.rs, src/server/services/graphql/schema/types.rs
=> Add type field to requisition table

migrations/20210607021315_create_transact_table.sql, sqlx-data.json, src/database/queries.rs, src/database/schema.rs, src/server/services/graphql/schema/types.rs
=> #119 Add type_of field to transact table

src/server/services/graphql/schema/types.rs
=> #129 Implement From traits

migrations/20210621235905_create_user_account_table.sql
=> Add user_account table to database

migrations/20210621235905_create_user_account_table.sql, src/database/connection.rs, src/database/queries.rs, src/database/schema.rs
=> Add user_account database queries

src/database/connection.rs, src/database/queries.rs
=> #140 Add customer invoice database queries

migrations/20210607021315_create_transact_table.sql
=> #142 fix transact missing store_id

src/database/connection.rs, src/database/queries.rs
=> Add transact database setters

src/server/services/graphql/schema/types.rs
=> Add CustomerInvoice gql queries

sqlx-data.json, src/database/mocks.rs
Fixes #153 , #155
This allows me to start compiling again! 🎉
=> #153 add sqlx-data.json update

src/database/schema.rs
=> Fix incorrect type_of mappings

migrations/20210607022626_create_transact_line_table.sql, src/database/mocks.rs, src/database/queries.rs, src/database/schema.rs
=> Add type_of field to transact_line table

migrations/20210606073020_create_item_table.sql, src/database/mocks.rs, src/database/queries.rs, src/database/schema.rs, src/server/services/graphql/schema/mutations.rs, src/server/services/graphql/schema/types.rs
=> Add type_of field to item table

README.md
=> #19 Add comments for new Rustaceans

Cargo.lock, Cargo.toml, src/database/connection.rs, src/main.rs, src/util/settings.rs, tests/graphql.rs, tests/mocks.rs
=> #179 Add example gql test

src/main.rs, tests/graphql.rs, tests/mocks.rs, tests/rest.rs
=> #200 Move mock repositories into tests

src/main.rs, src/server/data/registry.rs, src/server/service/graphql/schema/mutations.rs, src/server/service/graphql/schema/queries.rs, src/server/service/graphql/schema/types.rs, tests/graphql.rs, tests/mocks.rs
=> #202 Update RepositoryRegistry struct with optional fields

migrations/20210601032959_create_requisition_table.sql, migrations/20210601033207_create_requisition_line_table.sql, migrations/20210606073020_create_item_table.sql, migrations/20210606091546_create_item_line_table.sql, migrations/20210607021315_create_transact_table.sql, migrations/20210607022626_create_transact_line_table.sql, migrations/20210607023648_create_name_table.sql, migrations/20210607024352_create_store_table.sql, migrations/20210607062556_create_requisition_line_foreign_keys.sql, migrations/20210607063531_create_requisition_foreign_keys.sql, migrations/20210607064304_create_transact_foreign_keys.sql, migrations/20210607235510_create_item_line_foreign_keys.sql, migrations/20210607235848_create_transact_line_foreign_keys.sql, migrations/20210608000531_create_store_foreign_keys.sql, migrations/20210621235905_create_user_account_table.sql, migrations/20210713030858_create_sync_out_table.sql
=> #208 Add tables required by sync

docs/static/CNAME
=> Add dev.msupply.foundation CNAME

src/main.rs, src/server/data/registry.rs, src/server/service/rest/mod.rs, src/util/mod.rs, src/util/sync.rs
=> #211 Extract sync logic from main.rs

.github/workflows/build_docs_site.yml
=> #231 Doc action trigger

README.md, src/util/configuration.rs
=> #246 Add default APP_ENVIRONMENT

src/database/repository/mock/item.rs, src/database/repository/pgsqlx/item.rs, src/server/service/graphql/schema/queries.rs
=> #249 Add items query

src/database/repository/mock/mod.rs, src/database/repository/mod.rs, src/database/repository/pgsqlx/mod.rs, src/main.rs
=> #248 Tidy up main.rs

docs/content/docs/api/_index.md, docs/content/docs/api/filtering-pagination-sorting.md, docs/content/docs/api/filtering.md, docs/content/docs/api/mutations.md, docs/content/docs/api/queries.md
Fixes #254 
- Went with just filtering on this page
- I just copy pasted stuff, I don't really know how this works, if there's stuff that shouldn't be there, feel free to remove!
- We should choose a language to write code examples in the documentation?
- If there are updates it is easier to just commit to the branch rather than go back and forward, please!
=> #254 graphql filtering documentation

.github/workflows/build_docs_site.yml
Fixes #274 
No idea what I'm doing 🙃
=> #274 correct git hub action yml syntax

docs/content/docs/api/sorting.md
Fixes #276 
- Simple sorting!
- If there are any errors/mistakes/grammar issues please feel free to commit to the branch
=> #276 Add sorting docs

Cargo.lock, Cargo.toml, src/database/repository/diesel/mod.rs, src/database/repository/mod.rs, src/database/repository/pgsqlx/mod.rs
Closes #284.
Thanks to Chris M. for suggesting thiserror.
=> #284 Make RepositoryError an enum

docs/content/docs/api/patterns.md, docs/content/docs/api/queries.md
Partial fix to #281
As per discussion, just using first and offset 
* Use first and offset
* As page object rather then individual argument
=> #281  Api pattern pagination

Cargo.lock, Cargo.toml, src/util/settings.rs, tests/repository/test_db.rs
- Use bundled sqlite lib
- Fix feature name
=> [No issue] Fix sqlite tests

migrations/postgres/00000102_create_user_account/up.sql, migrations/postgres/00000103_create_name_table/up.sql, migrations/postgres/00000104_create_store_table/up.sql, migrations/postgres/00000105_create_item_table/up.sql, migrations/postgres/00000106_create_item_line_table/up.sql, migrations/postgres/00000107_create_transact_table/up.sql, migrations/postgres/00000108_create_transact_line_table/up.sql, migrations/postgres/00000109_create_requisition_table/up.sql, migrations/postgres/00000110_create_requisition_line_table/up.sql, migrations/postgres/00000111_create_sync_out_table/up.sql, src/database/repository/diesel/sync_out.rs, src/database/schema/diesel_schema.rs, src/database/schema/mod.rs, src/database/schema/sync_out.rs
=> #309 Regenerate diesel schema

.github/workflows/tests.yml, src/database/schema/diesel_schema.rs
Closes #288.
I configured this action to run on a pull request to main. Should we do the same for the docs?
=> #288 Add testing github action

src/database/repository/diesel/store.rs, src/database/repository/diesel/sync.rs, src/database/repository/mod.rs, src/util/sync/translation/mod.rs, src/util/sync/translation/name.rs, src/util/sync/translation/store.rs
Question: should find_one_by_id be replaced by find_one_by_id_joined (keeping the name)? I think that is what we want here, right?
I am aware of test location and unused struct definitions concerns, will look into it later...
=> 281 simple translation full (Store)

docs/content/docs/api/custom_errors.md, docs/content/docs/api/patterns.md
Partial fix to:
#286 
* Add error pattern description
* Added custom errors section for all errors
=> #286 Error handling patterns and custom error list

src/database/repository/diesel/central_sync_buffer.rs, src/database/repository/diesel/item.rs, src/database/repository/diesel/item_line.rs, src/database/repository/diesel/name.rs, src/database/repository/diesel/requisition.rs, src/database/repository/diesel/requisition_line.rs, src/database/repository/diesel/store.rs, src/database/repository/diesel/sync.rs, src/database/repository/diesel/transact.rs, src/database/repository/diesel/transact_line.rs, src/database/repository/diesel/user_account.rs, src/server/data/repository.rs, src/server/service/graphql/mod.rs
Closes #316.
Edit: apologies for the branch typo!
=> #316 Remove AnyRepository trait AnyClone

migrations/postgres/00000103_create_name_table/up.sql, migrations/postgres/00000104_create_store_table/up.sql, migrations/postgres/00000105_create_item_table/up.sql, migrations/sqlite/00000102_create_name_table/up.sql, migrations/sqlite/00000103_create_store_table/up.sql, migrations/sqlite/00000104_create_item_table/up.sql, src/database/mock/item.rs, src/database/mock/name.rs, src/database/mock/store.rs, src/database/schema/diesel_schema.rs, src/database/schema/item.rs, src/database/schema/name.rs, src/database/schema/store.rs, src/server/service/graphql/schema/mutations.rs, src/util/sync/translation/item.rs, src/util/sync/translation/name.rs, src/util/sync/translation/store.rs, src/util/sync/translation/test_data/item.rs, src/util/sync/translation/test_data/name.rs, src/util/sync/translation/test_data/store.rs, tests/repository/basic.rs
Add code, is_customer and is_supplier to existing tables
=> Add additional columns to item, name and store

src/util/sync/central.rs, src/util/sync/connection.rs, src/util/sync/mod.rs, src/util/sync/remote.rs, src/util/sync/server.rs, tests/sync.rs
=> #328 Add logic for pulling records from central_records endpoint

Cargo.lock, Cargo.toml, migrations/postgres/00000107_create_invoice_table/up.sql, src/database/mock/invoice.rs, src/database/repository/tests.rs, src/database/schema/diesel_schema.rs, src/database/schema/invoice.rs, src/util/test_db.rs
=> 356 invoice datetime

docs/content/docs/this_doc/info.md
=> update docs info.md

src/util/test_db.rs
This helps to keep the project directory clean.
=> Store sqlite test db files in test_output directory

Cargo.lock, Cargo.toml, src/database/repository/diesel/invoice_query.rs, src/database/repository/diesel/mod.rs, src/server/service/graphql/schema/queries/mod.rs, src/server/service/graphql/schema/types/invoice_query.rs, src/server/service/graphql/schema/types/invoices.rs, src/server/service/graphql/schema/types/mod.rs, src/util/datetime.rs, src/util/mod.rs, tests/graphql/invoice_query.rs, tests/graphql/mod.rs
Still to come:
- Unified InvoiceNode for invoices and invoice
- Schema changes Decimal -> Double, expiry date
=> Implement the invoice GraphQL endpoint

src/database/repository/diesel/mod.rs, src/database/repository/diesel/name_query.rs, src/database/repository/tests.rs, src/server/service/graphql/schema/queries/mod.rs, src/server/service/graphql/schema/types/name.rs
=> 305 Add sort option for the name query

src/database/repository/diesel/mod.rs, src/database/repository/diesel/name_query.rs, src/database/repository/tests.rs, src/server/service/graphql/schema/queries/mod.rs, src/server/service/graphql/schema/types/name.rs
=> 306 name filters

src/database/repository/diesel/item_query.rs, src/database/repository/diesel/mod.rs, src/server/service/graphql/schema/queries/mod.rs, src/server/service/graphql/schema/types/invoices_query.rs, src/server/service/graphql/schema/types/item.rs, src/server/service/graphql/schema/types/name.rs, src/server/service/graphql/schema/types/sort_filter_types.rs
Add filter and sort for items
Some refactoring:
- Move item gql related code to the graphql dir
- Add a generic From implementation for the Sort option
Closes #393
=> 393 items filter sort

src/database/repository/diesel/item_query.rs, src/domain/item.rs, src/domain/mod.rs, src/server/service/graphql/schema/queries/mod.rs, src/server/service/graphql/schema/types/item.rs, src/server/service/graphql/schema/types/mod.rs, src/server/service/graphql/schema/types/sort_filter_types.rs, src/service/item.rs, src/service/mod.rs
Fixes: #405 
Extending changes in [this pr](https://github.com/openmsupply/remote-server/pull/407), to apply to item query
Branch name is wrong, should save align item
=> 405 align item query with design decisions

src/server/service/graphql/schema/mutations/customer_invoice/error.rs, src/server/service/graphql/schema/mutations/customer_invoice/insert.rs, src/server/service/graphql/schema/mutations/customer_invoice/update.rs, tests/graphql/customer_invoice_insert.rs, tests/graphql/mod.rs
=> 464 ci insert test

src/server/service/graphql/schema/queries/mod.rs, src/server/service/graphql/schema/types/mod.rs, src/server/service/graphql/schema/types/name.rs, src/server/service/graphql/schema/types/sort_filter_types.rs
=> Add some API doc comments and fix page limit field

src/server/service/graphql/schema/mutations/inbound_shipment/delete.rs, src/server/service/graphql/schema/mutations/inbound_shipment/insert.rs, src/server/service/graphql/schema/mutations/inbound_shipment/line/delete.rs, src/server/service/graphql/schema/mutations/inbound_shipment/line/insert.rs, src/server/service/graphql/schema/mutations/inbound_shipment/line/mod.rs, src/server/service/graphql/schema/mutations/inbound_shipment/line/update.rs, src/server/service/graphql/schema/mutations/inbound_shipment/update.rs, src/server/service/graphql/schema/mutations/mod.rs, src/server/service/graphql/schema/mutations/outbound_shipment/delete.rs, src/server/service/graphql/schema/mutations/outbound_shipment/insert.rs, src/server/service/graphql/schema/mutations/outbound_shipment/line/delete.rs, src/server/service/graphql/schema/mutations/outbound_shipment/line/insert.rs, src/server/service/graphql/schema/mutations/outbound_shipment/line/mod.rs, src/server/service/graphql/schema/mutations/outbound_shipment/line/update.rs, src/server/service/graphql/schema/mutations/outbound_shipment/update.rs, src/server/service/graphql/schema/queries/mod.rs, src/server/service/graphql/schema/types/invoice_line.rs, src/server/service/graphql/schema/types/invoice_query.rs, src/server/service/graphql/schema/types/item.rs, src/server/service/graphql/schema/types/name.rs, src/server/service/graphql/schema/types/stock_line.rs
Closes #523 
As per commit description.
Actually ended up being less lines and easier to navigate to implementation
Wanted to do this before jumping into: https://github.com/openmsupply/remote-server/issues/509
=> Remove all From<Result> traits

src/server/service/graphql/schema/mutations/inbound_shipment/batch.rs, src/server/service/graphql/schema/mutations/inbound_shipment/delete.rs, src/server/service/graphql/schema/mutations/inbound_shipment/insert.rs, src/server/service/graphql/schema/mutations/inbound_shipment/line/delete.rs, src/server/service/graphql/schema/mutations/inbound_shipment/line/insert.rs, src/server/service/graphql/schema/mutations/inbound_shipment/line/update.rs, src/server/service/graphql/schema/mutations/inbound_shipment/mod.rs, src/server/service/graphql/schema/mutations/inbound_shipment/update.rs, src/server/service/graphql/schema/mutations/mod.rs
Part of 509.
@clemens-msupply what do you think of use of macro here ? the alternative can be achieved with traits and quite complex trait bound.
=> Add batched inbound shipment mutation

src/server/service/graphql/schema/mutations/mod.rs, src/server/service/graphql/schema/mutations/outbound_shipment/batch.rs, src/server/service/graphql/schema/mutations/outbound_shipment/delete.rs, src/server/service/graphql/schema/mutations/outbound_shipment/insert.rs, src/server/service/graphql/schema/mutations/outbound_shipment/line/delete.rs, src/server/service/graphql/schema/mutations/outbound_shipment/line/insert.rs, src/server/service/graphql/schema/mutations/outbound_shipment/line/update.rs, src/server/service/graphql/schema/mutations/outbound_shipment/mod.rs, src/server/service/graphql/schema/mutations/outbound_shipment/update.rs
Partially fixes 509
Just replicated changes in this [pr](https://github.com/openmsupply/remote-server/pull/525) but for outbound shipments
=> 509 batched outbound shipment

Cargo.lock, Cargo.toml, migrations/postgres/00000101_create_user_account/up.sql, migrations/sqlite/00000101_create_user_account/up.sql, src/database/repository/diesel/user_account.rs, src/database/repository/tests.rs, src/service/mod.rs, src/service/token_bucket.rs, src/service/user_account.rs
Plan to implement logout while I am on it in a different PR
I used a UserAccountService struct since I plan to have a "TokenBucket" for logout which I like to pass in when creating the UserAccountService...
=> 506 account creation, token verification and refresh (service only)

src/service/token_bucket.rs
This should have been part of the previous PR but got interrupted and missed to commit it...
=> Add some docs and code refactoring

configuration/base.yaml, configuration/local.yaml, configuration/production.yaml, src/util/settings.rs, src/util/sync/connection.rs, src/util/sync/server.rs, src/util/test_db.rs
Add option to use https to connect to the central server for sync .
Not sure about local and production config. Is that ok as I did it?
=> Use an url to specify the sync server

graphql_schema/query.graphql, graphql_schema/schema.graphql, migrations/postgres/00000105_create_stock_line_table/up.sql, migrations/sqlite/00000105_create_stock_line_table/up.sql, src/database/mock/full_invoice.rs, src/database/mock/stock_line.rs, src/database/repository/diesel/stock_line.rs, src/database/repository/tests.rs, src/database/schema/diesel_schema.rs, src/database/schema/stock_line.rs, src/domain/stock_line.rs, src/server/service/graphql/schema/mutations/outbound_shipment/line/insert.rs, src/server/service/graphql/schema/mutations/outbound_shipment/line/mod.rs, src/server/service/graphql/schema/mutations/outbound_shipment/line/update.rs, src/server/service/graphql/schema/types/stock_line.rs, src/service/invoice/inbound_shipment/update/generate.rs, src/service/invoice/outbound_shipment/update/generate.rs, src/service/invoice_line/inbound_shipment_line/mod.rs, src/service/invoice_line/outbound_shipment_line/insert/mod.rs, src/service/invoice_line/outbound_shipment_line/insert/validate.rs, src/service/invoice_line/outbound_shipment_line/update/mod.rs, src/service/invoice_line/outbound_shipment_line/update/validate.rs, src/service/invoice_line/outbound_shipment_line/validate.rs, tests/graphql/outbound_shipment_line_insert.rs, tests/graphql/outbound_shipment_line_update.rs
Closes #538
Added on hold to stock line row and error when outbound shipment line mutations try to use stock line that is on hold
=> 538 add on hold to stock line

graphql_schema/query.graphql, graphql_schema/schema.graphql, migrations/postgres/00000105_create_stock_line_table/up.sql, migrations/postgres/00000107_create_invoice_line_table/up.sql, migrations/sqlite/00000105_create_stock_line_table/up.sql, migrations/sqlite/00000107_create_invoice_line_table/up.sql, src/database/mock/full_invoice.rs, src/database/mock/invoice_line.rs, src/database/mock/stock_line.rs, src/database/repository/diesel/invoice_line_query.rs, src/database/repository/diesel/stock_line.rs, src/database/repository/tests.rs, src/database/schema/diesel_schema.rs, src/database/schema/invoice_line.rs, src/database/schema/stock_line.rs, src/domain/invoice_line.rs, src/domain/stock_line.rs, src/server/service/graphql/schema/types/invoice_line.rs, src/server/service/graphql/schema/types/stock_line.rs, src/service/invoice/inbound_shipment/update/generate.rs, src/service/invoice/outbound_shipment/update/generate.rs, src/service/invoice_line/inbound_shipment_line/insert/generate.rs, src/service/invoice_line/inbound_shipment_line/mod.rs, src/service/invoice_line/outbound_shipment_line/insert/generate.rs, src/service/invoice_line/outbound_shipment_line/update/generate.rs, tests/graphql/inbound_shipment_update.rs, tests/graphql/outbound_shipment_line_insert.rs, tests/graphql/outbound_shipment_line_update.rs
Closes: #540 
As per issue, add note and appropriate transfers of note from stock line to invoice line (outbound shipment) and invoice line to stock line (inbound shipment)
=> 540 add invoice line note

src/database/loader/diesel.rs, src/database/loader/mod.rs, src/database/loader/name.rs, src/database/repository/diesel/item_query.rs, src/database/repository/diesel/name_query.rs, src/domain/invoice.rs, src/domain/invoice_line.rs, src/domain/mod.rs, src/domain/name.rs, src/domain/stock_line.rs, src/server/service/graphql/schema/types/invoice_query.rs, src/server/service/graphql/schema/types/mod.rs, src/server/service/graphql/schema/types/name.rs, src/server/service/graphql/schema/types/sort_filter_types.rs, tests/graphql/invoice_query.rs
Closes: #545 
Also addd equal_any (in) to domain filters, since I wanted to use query in NameQueryRepository because type of otherParty is of NameNode (which comes from Name domain object, and NameQueryRepository provides it, rather then NameRow provided by NameRepository)
=> 545 add other party to invoice node

src/database/repository/diesel/invoice_query.rs, src/domain/invoice.rs, src/server/service/graphql/schema/types/invoice_query.rs, src/server/service/graphql/schema/types/sort_filter_types.rs, tests/graphql/invoices.rs
Closes #547 
Decided to group equal filters into generic derives (as it was done for other input object in sort_filter file
=> 547 add invoice number to invoice filter

src/database/repository/diesel/invoice_query.rs, src/domain/invoice.rs, src/server/service/graphql/schema/types/invoice_query.rs, tests/graphql/invoices.rs
Closes #550 
Added macro in tests. But had issues with tests for Option (comment) and for date time (since default serialization of NaiveDateTime is different to the one in graphql type (didn't think sort test are high enough priority to pursue further)
=> 550 add more sorts field to invoices

graphql_schema/schema.graphql, src/server/service/graphql/schema/mutations/mod.rs, src/server/service/graphql/schema/types/invoice_query.rs, src/server/service/graphql/schema/types/item.rs, src/server/service/graphql/schema/types/mod.rs, src/server/service/graphql/schema/types/name.rs, tests/graphql/invoices.rs, tests/graphql/names.rs, tests/graphql/outbound_shipment_insert.rs
=> 549 camel case enums for table or field names

docs/content/docs/M1/_index.md, docs/content/docs/api/_index.md, docs/content/docs/getting-started/_index.md, docs/content/docs/preferences/_index.md, docs/content/docs/preferences/api.md, docs/content/docs/preferences/database.md, docs/content/docs/preferences/logic.md, docs/content/docs/preferences/sync.md, docs/content/docs/this_doc/_index.md
Do the zola docs get auto-built from develop or main? I just branched from main without thinking, sorry.
This is just a draft docs for [preferences]. I've added a new folder for preferences specifically. Thought this was enough to PR and get feedback before I did anything else.
=> #preference docs

server/src/util/sync/synchroniser.rs
=> Fix warnings

repository/src/test_db.rs, service/Cargo.toml
Two problems:
- sqlite feature was not set for service tests
- In the IDE tests a run from the project root dir -> fix search for
migration files
=> Fix tests when run from VSCode

graphql/src/schema/mutations/inbound_shipment/insert.rs, graphql/src/schema/mutations/inbound_shipment/line/insert.rs, graphql/src/schema/mutations/inbound_shipment/line/update.rs, graphql/src/schema/mutations/inbound_shipment/update.rs, graphql/src/schema/mutations/outbound_shipment/insert.rs, graphql/src/schema/mutations/outbound_shipment/line/insert.rs, graphql/src/schema/mutations/outbound_shipment/line/update.rs, graphql/src/schema/mutations/outbound_shipment/update.rs
Surprising easy to remove the macro!
For the NodeError when getting the invoice/line after mutating the invoice/line. I think if we put the whole mutation into a transaction we can remove the error and merge it into the invoice/line error? i.e. if we fail to retrieve the invoice/line than it is an internal error that shouldn't really happen.
Related, do we actually need to get the invoice/line after mutating it? isn't it enough to return the mutated invoice/line.
=> Remove #[graphql(flatten)]

graphql/src/schema/queries/me.rs, service/src/permission_validation.rs
- Global permission setup
- Introduce a ValidationService (needed for testing to swap out the
global permissions)
- Remove StorageConnection setup since this would be replaced when using
a service factory.
Still a bit verbose, may another validation helper method once we have
the service factory (?)...
=> Use a PermissionDSL struct instead of some checker functions

repository/migrations/postgres/00000104_create_item_table/up.sql, repository/migrations/sqlite/00000104_create_item_table/up.sql, repository/src/db_diesel/item_query.rs, repository/src/mock/item.rs, repository/src/schema/diesel_schema.rs, repository/src/schema/item.rs, repository/src/schema/mod.rs, server/src/sync/translation/item.rs, server/src/sync/translation/test_data/item.rs
Did I get the translation right?
```
LegacyItemType::non_stock => ItemType::NonStock,
LegacyItemType::service => ItemType::Service,
LegacyItemType::general => ItemType::Stock,
```
=> Add an item type

Cargo.lock, repository/Cargo.toml, repository/src/db_diesel/storage_connection.rs
I missed your comments from your previous PR
=> Tx test logging

graphql/src/schema/mutations/location/mod.rs, graphql/src/schema/mutations/location/update.rs, graphql/src/schema/mutations/mod.rs, graphql/src/schema/types/mod.rs, repository/src/db_diesel/storage_connection.rs, server/tests/graphql/location_update.rs, server/tests/graphql/mod.rs, service/src/invoice/inbound_shipment/insert/generate.rs, service/src/invoice/inbound_shipment/insert/mod.rs, service/src/invoice/inbound_shipment/update/generate.rs, service/src/invoice/outbound_shipment/insert/generate.rs, service/src/invoice/outbound_shipment/insert/mod.rs, service/src/invoice_line/inbound_shipment_line/generate.rs, service/src/invoice_line/inbound_shipment_line/insert/generate.rs, service/src/invoice_line/inbound_shipment_line/insert/mod.rs, service/src/invoice_line/inbound_shipment_line/update/generate.rs, service/src/invoice_line/inbound_shipment_line/update/mod.rs, service/src/lib.rs, service/src/location/insert/generate.rs, service/src/location/insert/mod.rs, service/src/location/insert/tests.rs, service/src/location/insert/validate.rs, service/src/location/mod.rs, service/src/location/update/generate.rs, service/src/location/update/mod.rs, service/src/location/update/tests.rs, service/src/location/update/validate.rs, service/src/location/validate.rs, service/src/service_provider.rs, service/src/validate.rs
Closes: #620 
Pretty straight forward, copy paste really
=> 620 update location mutation

graphql/src/schema/mutations/mod.rs, graphql/src/schema/mutations/outbound_shipment/batch.rs, graphql/src/schema/mutations/outbound_shipment/mod.rs, graphql/src/schema/mutations/outbound_shipment/service_line/delete.rs, graphql/src/schema/mutations/outbound_shipment/service_line/insert.rs, graphql/src/schema/mutations/outbound_shipment/service_line/mod.rs, graphql/src/schema/mutations/outbound_shipment/service_line/update.rs, graphql/src/schema/types/mod.rs, repository/src/mock/mod.rs, service/Cargo.toml, service/src/invoice_line/mod.rs, service/src/invoice_line/outbound_shipment_service_line/delete/mod.rs, service/src/invoice_line/outbound_shipment_service_line/delete/validate.rs, service/src/invoice_line/outbound_shipment_service_line/insert/generate.rs, service/src/invoice_line/outbound_shipment_service_line/insert/mod.rs, service/src/invoice_line/outbound_shipment_service_line/insert/validate.rs, service/src/invoice_line/outbound_shipment_service_line/mod.rs, service/src/invoice_line/outbound_shipment_service_line/update/generate.rs, service/src/invoice_line/outbound_shipment_service_line/update/mod.rs, service/src/invoice_line/outbound_shipment_service_line/update/validate.rs
Just the service part.
Is location a thing for service lines?
Shouldn't we have a separate table for service lines? the existing row doesn't seem a good fit since many fields are unused for service lines...
=> 569 outbound service item

domain/src/item.rs, graphql/src/loader/item.rs, graphql/src/schema/types/invoice_line.rs, graphql/src/schema/types/item.rs, repository/src/db_diesel/item_query.rs
As discussed this adds items() to invoice lines
=> 568 gql invoice lines item

graphql/src/schema/queries/invoice_counts.rs, graphql/src/schema/queries/mod.rs, service/src/dashboard/invoice_count.rs
Restructured the endpoint a little bit. The gql errors make it quite easy :) (still using temp gql errors, will update later)
=> 579 outbound shipment counts

Cargo.lock, domain/src/lib.rs, domain/src/stock_line.rs, graphql/Cargo.toml, graphql/src/schema/queries/invoice_counts.rs, graphql/src/schema/queries/mod.rs, graphql/src/schema/queries/stock_counts.rs, repository/src/db_diesel/stock_line.rs, repository/src/mock/mod.rs, repository/src/tests.rs, server/tests/graphql/master_lists.rs, service/src/dashboard/invoice_count.rs, service/src/dashboard/mod.rs, service/src/dashboard/stock_expiry_count.rs, service/src/service_provider.rs, util/Cargo.toml, util/src/lib.rs, util/src/timezone.rs
Add count_stock endpoint and refactor count_invoices a little bit.
Closes #579
=> 579 stock expiry

graphql/src/schema/mutations/outbound_shipment/update.rs, server/tests/graphql/outbound_shipment_update.rs, service/src/invoice/outbound_shipment/update/mod.rs, service/src/invoice/outbound_shipment/update/validate.rs, service/src/invoice_line/mod.rs, service/src/invoice_line/outbound_shipment_unallocated_line/delete.rs, service/src/invoice_line/outbound_shipment_unallocated_line/mod.rs, service/src/invoice_line/outbound_shipment_unallocated_line/update.rs, service/src/invoice_line/validate.rs
Closes #665 
Coses #666 
Closes #669
Should be pretty straight forward, as per the issues
=> 665 666 669 unallocated line delete/update service and outbound shipment status update restriction

repository/src/mock/mod.rs, repository/src/mock/test_unallocated_line.rs, service/src/invoice/outbound_shipment/update/generate.rs, service/src/invoice/outbound_shipment/update/mod.rs, service/src/invoice_line/outbound_shipment_service_line/update/generate.rs, service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
I've merged chained branches without updating them from each other (ended up overriding changes that were done in upstream branches), this PR fixes that
=> 665 666 669 fix merge with updates from previous branches

service/src/lib.rs
Closes #678
As per commit comment
=> 678 Fix bug with finding store id

server/tests/graphql/inbound_shipment_line_update.rs, service/src/invoice_line/inbound_shipment_line/update/generate.rs
=> 677 fix inbound line update location

domain/src/invoice.rs, graphql/src/loader/invoice.rs, graphql/src/loader/loader_registry.rs, graphql/src/schema/types/invoice_query.rs, repository/src/db_diesel/invoice_query.rs, repository/src/mock/mod.rs, repository/src/mock/test_invoice_loaders.rs, server/tests/graphql/invoice_by_number.rs, server/tests/graphql/invoice_loaders.rs, server/tests/graphql/mod.rs, server/tests/graphql/requisition/response_requisition/create_requisition_shipment.rs
closes #731 
Pretty straight forward, I did remove one unused loader (and checked all other loaders if they are used or not)
=> 737 Add linked invoice and requisition loader for invoice

server/src/sync/mod.rs, server/src/sync/remote_data_synchroniser.rs, server/src/sync/translation_remote/mod.rs, server/src/sync/translation_remote/name_store_join.rs, server/src/sync/translation_remote/shipment.rs, server/src/sync/translation_remote/shipment_line.rs, server/src/sync/translation_remote/stocktake.rs, server/src/sync/translation_remote/stocktake_line.rs, server/src/sync/translation_remote/test_data/mod.rs, server/src/sync/translation_remote/test_data/name_store_join.rs, server/src/sync/translation_remote/test_data/number.rs, server/src/sync/translation_remote/test_data/stock_line.rs, server/src/sync/translation_remote/test_data/stocktake.rs, server/src/sync/translation_remote/test_data/stocktake_line.rs, server/src/sync/translation_remote/test_data/trans_line.rs, server/src/sync/translation_remote/test_data/transact.rs
Sync pull for stocktake and stocktake line
=> 714 stock take pull

repository/src/db_diesel/name_store_join.rs, server/src/sync/central_data_synchroniser.rs
=> Remove manual name store join creation

graphql/graphql_schema/query.graphql, graphql/graphql_schema/schema.graphql, graphql/src/schema/types/invoice_line.rs, graphql/src/schema/types/invoice_query.rs, graphql/src/schema/types/master_list.rs, graphql/src/schema/types/stock_line.rs, server/tests/graphql/inbound_shipment_line_insert.rs, server/tests/graphql/inbound_shipment_line_update.rs
#781 
Even though it's not quite in scope for the issue, it would reduce f/e changes.
=> 781 remove nested unions for single record resolvers

service/src/requisition_line/common.rs, service/src/requisition_line/request_requisition_line/insert.rs
=> 826 allow same item in multiple requisitions

graphql/graphql_schema/query.graphql, graphql/graphql_schema/schema.graphql, graphql/src/mutations.rs, graphql/src/queries.rs, server/tests/graphql/inbound_shipment_batch.rs, server/tests/graphql/item_stats.rs, server/tests/graphql/items.rs, server/tests/graphql/locations.rs, server/tests/graphql/master_lists.rs, server/tests/graphql/names.rs, server/tests/graphql/outbound_shipment_delete.rs, server/tests/graphql/outbound_shipment_update.rs, server/tests/graphql/pagination.rs, server/tests/graphql/unallocated_line/delete.rs, server/tests/graphql/unallocated_line/insert.rs, server/tests/graphql/unallocated_line/update.rs
=> 837 Add store_id parameters to all end points

graphql/requisition/src/mutations/request_requisition/insert.rs, graphql/requisition/src/mutations/request_requisition/update.rs, graphql/requisition/src/query_tests/requisition_loaders.rs, graphql/requisition_line/src/mutations/request_requisition_line/insert.rs, graphql/requisition_line/src/mutations/request_requisition_line/update.rs, graphql/requisition_line/src/mutations/response_requisition_line/update.rs, graphql/types/src/types/requisition_line.rs, repository/migrations/postgres/2021-09-18T10-00_create_requisition_line table/up.sql, repository/migrations/sqlite/2021-09-18T10-00_create_requisition_line_table/up.sql, repository/src/mock/test_requisition_line_repository.rs, repository/src/mock/test_requisition_queries.rs, repository/src/mock/test_requisition_service.rs, repository/src/mock/test_sync_processor.rs, repository/src/schema/diesel_schema.rs, repository/src/schema/requisition_line.rs, service/src/requisition/request_requisition/generate.rs, service/src/requisition/request_requisition/insert.rs, service/src/requisition/request_requisition/mod.rs, service/src/requisition/request_requisition/update/generate.rs, service/src/requisition/request_requisition/update/mod.rs, service/src/requisition/request_requisition/update/test.rs, service/src/requisition/request_requisition/update/validate.rs, service/src/requisition/request_requisition/validate.rs, service/src/requisition/response_requisition/create_requisition_shipment/test.rs, service/src/requisition_line/request_requisition_line/insert.rs, service/src/requisition_line/request_requisition_line/update.rs, service/src/requisition_line/response_requisition_line/update.rs, service/src/sync_processor/requisition/common.rs, util/src/to_inline_init.js
closes #807 
Only ran the script on files that i've touched that needed extra struct field added and fixed the script (it was considering anything ending with 0, as default value
=> 870 requisition line comment

graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/delete.rs, graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/insert.rs, graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/update.rs, repository/src/db_diesel/item_query.rs, repository/src/mock/item.rs, service/src/invoice_line/outbound_shipment_service_line/delete/mod.rs, service/src/invoice_line/outbound_shipment_service_line/insert/generate.rs, service/src/invoice_line/outbound_shipment_service_line/insert/mod.rs, service/src/invoice_line/outbound_shipment_service_line/insert/validate.rs, service/src/invoice_line/outbound_shipment_service_line/update/mod.rs, util/src/constants.rs, util/src/to_inline_init.js
=> 872 Change insert service line to allow for default service item

graphql/requisition/src/mutations/request_requisition/insert.rs, graphql/requisition/src/mutations/request_requisition/update.rs, service/src/requisition/request_requisition/insert.rs, service/src/requisition/request_requisition/mod.rs, service/src/requisition/request_requisition/update/generate.rs, service/src/requisition/request_requisition/update/mod.rs, service/src/requisition/request_requisition/update/test.rs, service/src/requisition/request_requisition/update/validate.rs, service/src/requisition/request_requisition/validate.rs
=> 804 Add other party id to request requisition update

server/src/sync/synchroniser.rs
Push can corrupt dates on the central server right now...
=> Disable remote data push till more testing has been done

graphql/types/src/types/store.rs
=> Add name resolver to StoreNode

service/src/invoice/inbound_shipment/batch.rs
Messed it up in the mass merge, I should check dev after merge next time
=> Fix compiltaion

graphql/printing/src/lib.rs
=> Add missing report id

graphql/types/src/types/invoice_line.rs
=> 896 expose pricing on invoice line node

graphql/core/src/generic_filters.rs, graphql/general/src/queries/item.rs, graphql/general/src/queries/master_list.rs, graphql/general/src/queries/names.rs, graphql/invoice/src/invoice_queries.rs, graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs, graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/insert.rs, graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs, graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/insert.rs, graphql/location/src/lib.rs, graphql/requisition/src/requisition_queries.rs, graphql/stocktake/src/stocktake_queries.rs, graphql/types/src/types/item.rs, graphql/types/src/types/stock_line.rs, repository/src/db_diesel/invoice_query.rs, repository/src/db_diesel/item_query.rs, repository/src/db_diesel/key_value_store.rs, repository/src/db_diesel/requisition/mod.rs, repository/src/db_diesel/requisition/requisition.rs
closes #892
changes as per commits
=> 892 minor api changes

server/src/sync/translation_remote/pull.rs
Reference: https://github.com/openmsupply/remote-server/issues/919
Going to merge now and revisit on monday
=> Ignore failed translations

server/src/sync/sync_api_v5.rs, server/src/sync/translation_remote/pull.rs
Just some smaller fixes:
- return when remote pull translation succeeded (don't print warning that it didn't)
- some API fixes for insert and delete records
=> 714 pull fixes

server/src/sync/translation_remote/invoice.rs
Some of this will be refactored once we have missing fields in mSupply.
Not sure about the invad status mapping (was just guessing but as far as I remembered they where only new and finalised?)
=> Add support to sync inventory adjustments

Cargo.lock, android/Cargo.toml, android/src/android.rs, graphql/Cargo.toml, graphql/batch_mutations/Cargo.toml, graphql/core/Cargo.toml, graphql/core/src/loader/loader_registry.rs, graphql/core/src/standard_graphql_error.rs, graphql/core/src/test_helpers.rs, graphql/general/Cargo.toml, graphql/invoice/Cargo.toml, graphql/invoice_line/Cargo.toml, graphql/lib.rs, graphql/location/Cargo.toml, graphql/reports/Cargo.toml, graphql/requisition/Cargo.toml, graphql/requisition_line/Cargo.toml, graphql/stocktake/Cargo.toml, graphql/stocktake_line/Cargo.toml, graphql/types/Cargo.toml, repository/Cargo.toml, server/Cargo.toml, server/src/lib.rs, server/src/static_files.rs, service/Cargo.toml
=> 944 upgrade async graqphl and actix

graphql/types/src/types/invoice_query.rs, repository/migrations/postgres/2021-10-05T10-00_create_invoice_stats_view/up.sql, repository/migrations/sqlite/2021-10-05T10-00_create_invoice_stats_view/up.sql, repository/src/tests.rs
closes #917 
as per issue and related comment
=> 917 Fix tax percentage calculation on invoice

graphql/requisition/src/mutations/response_requisition/create_requisition_shipment.rs, graphql/stocktake/src/mutations/update.rs, graphql/types/src/types/invoice_query.rs, graphql/types/src/types/requisition.rs, graphql/types/src/types/stocktake.rs, service/src/requisition/mod.rs, service/src/requisition/response_requisition/create_requisition_shipment/generate.rs, service/src/requisition/response_requisition/create_requisition_shipment/mod.rs, service/src/requisition/response_requisition/create_requisition_shipment/test.rs, service/src/stocktake/batch.rs, service/src/stocktake/mod.rs, service/src/stocktake/update.rs, service/src/user_account.rs
=> 921 Remove get_default_user id

graphql/core/src/loader/requisition_supply_status.rs, graphql/requisition/src/query_tests/requisition_loaders.rs, graphql/types/src/types/requisition.rs, graphql/types/src/types/requisition_line.rs, repository/src/db_diesel/requisition/requisition.rs, repository/src/mock/common.rs, repository/src/mock/mod.rs, repository/src/mock/test_remaining_to_supply.rs
closes #925 
looks like i've copied the loader for requisitions line but didn't update it to use RequisitionLinesRemainingToSupplyLoader, also `RequisitionLinesRemainingToSupplyLoader` didn't return an array of lines.
Also added a test for remaining to supply
=> 925 Fix lines remaining to supply

service/src/invoice_line/outbound_shipment_unallocated_line/allocate/generate.rs, service/src/invoice_line/outbound_shipment_unallocated_line/allocate/test.rs
=> 966 Allocation should not use existing allocated lines

server/src/static_files.rs
=> 969 Fix routing for files end point

graphql/types/src/types/item_chart_data.rs
=> 958 requisition mock chart changes

graphql/core/src/loader/name.rs
Prevents potential bug where names from different stores are requested.
I did this because I thought I ran into this bug but that wasn't the case. Thought the change would be useful anyway.
=> NameByIdLoader: Fetch names for every store_id

repository/migrations/postgres/2022-01-27T08-00_create_changelog_table/up.sql, repository/migrations/postgres/2022-02-23T10-15_create_location_trigger/down.sql, repository/migrations/postgres/2022-02-23T10-15_create_location_trigger/up.sql, repository/migrations/sqlite/2022-01-27T08-00_create_changelog_table/up.sql, repository/migrations/sqlite/2022-02-23T10-15_create_location_trigger/down.sql, repository/migrations/sqlite/2022-02-23T10-15_create_location_trigger/up.sql, repository/src/schema/changelog.rs, server/src/sync/integration_tests/invoice.rs, server/src/sync/integration_tests/location.rs, server/src/sync/integration_tests/mod.rs, server/src/sync/integration_tests/remote_sync_integration_test.rs, server/src/sync/integration_tests/stock_line.rs, server/src/sync/integration_tests/stocktake.rs, server/src/sync/translation_remote/location.rs, server/src/sync/translation_remote/mod.rs, server/src/sync/translation_remote/pull.rs, server/src/sync/translation_remote/push.rs, server/src/sync/translation_remote/test_data/location.rs, server/src/sync/translation_remote/test_data/mod.rs
Add remote sync for location + tests + integration tests.
#987
=> 987 sync location

server/src/sync/integration_tests/invoice.rs, server/src/sync/translation_remote/invoice_line.rs, server/src/sync/translation_remote/test_data/mod.rs, server/src/sync/translation_remote/test_data/trans_line.rs
=> 987 remote sync optional tax

service/src/token.rs
Thought I write down the motivating thoughts we had on why use the current auth token setup.
=> Add some high level docs for the TokenService

service/src/login.rs
=> Add missing report mapping

server/src/static_files.rs
=> Use DispositionType::Inline for the files endpoint

server/src/sync/sync_api_v5.rs
=> Update sync v5 syncId and recordId members

graphql/location/src/lib.rs
=> Always filter locations by store_id

repository/migrations/postgres/2022-03-25T14-30_create_user_permission_table/up.sql, repository/migrations/sqlite/2022-03-25T14-30_create_user_permission_table/up.sql
Fixes #1052 
Just pop this in as a PR to clear my working directory 😉
=> Add SERVER_ADMIN permission

graphql/core/src/standard_graphql_error.rs, service/src/permission_validation.rs
@mark-prins I remember you are currently parsing the FORBIDDEN msg? would it break your code?
=> Show more details in the forbidden std msg

server/src/lib.rs
Instead of terminating when the initial sync failed restart into bootstrap mode.
To make this work the http server need to be bound to an ip address after the initial sync otherwise we get an addr in use error. This makes the PR look bigger than it is.
https://github.com/openmsupply/remote-server/issues/1046
=> Falling back to bootstrap mode if the initial sync failed

graphql/core/src/test_helpers.rs, server/src/lib.rs, service/src/auth_data.rs, service/src/login.rs, service/src/permission_validation.rs
- Users keep logged in after restart
- After restart the DB settings are preferred
Closes #1058
=> 1058 server settings fixes

.gitignore, android/src/android.rs, configuration/base.yaml, server/src/lib.rs, server/src/settings.rs, server/src/test_utils.rs
=> Remove permissive from CORS settings, and set Origin in Server Settings

graphql/core/src/simple_generic_errors.rs, graphql/core/src/standard_graphql_error.rs, graphql/general/src/lib.rs, graphql/general/src/queries/logout.rs, graphql/graphql_schema/schema.graphql
=> #1054 Logout endpoint doesn't use std errors

README.md, configuration/base.yaml
=> Add CORS to readme, include http://localhost:8000 in defaults

configuration/base.yaml, graphql/core/src/generic_filters.rs, graphql/stocktake/src/stocktake_queries.rs, repository/src/db_diesel/stocktake.rs, repository/src/diesel_macros.rs
=> Stocktake query -- missing sort keys #981

Cargo.lock, android/Cargo.toml, android/src/android.rs, server/Cargo.toml, server/src/lib.rs, server/src/self_signed_certs.rs, server/src/settings.rs, server/src/test_utils.rs
- Add option to configure the certs directory
- Use rustls instead of openssl to avoid openssl issues on Android
Closes #1070
=> 1070 android tls

graphql/tests/mod.rs, graphql/tests/report_default_queries.rs, repository/src/test_db.rs, service/src/report/default_queries.rs, service/src/report/mod.rs
- Fix default report invoice query
Closes #1087
- Add basic default query test (just checks the query goes through)
Closes #1084
=> 1087 fix default invoice query

server/src/cors.rs, service/src/report/report_service.rs
Fixes #1082 
Update the report filename with windows-safe characters
=> Enable printing on windows

service/src/report/default_queries.rs
=> #1106 Added item and location field details for stocktake report template
